//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int Id { get; set; }
        public int IdUnits { get; set; }
        public int IdProductName { get; set; }
        public int IdSupplier { get; set; }
        public int IdCategory { get; set; }
        public string Article { get; set; }
        public string ProductDiscription { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public Nullable<int> DiscountNow { get; set; }
        public string PhotoName { get; set; }
        public byte[] ProductPhote { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Units Units { get; set; }
    }
}
